---
title: "Hub Activity"
---

### Reading discussion group
The OSTH hosts a reading discussion group that meets regularly during Oxford term time. 

#### Our reading list

### Upcoming events

#### Seminars

#### Workshops and trainings
There are no upcoming trainings currently scheduled. We are always happy for suggestions, so please let us know if you have ideas for trainings. 

### Previous events

#### Past seminars

*ONE Water event - details coming soon*

*INET seminar series, Hilary Term 2025 - details coming soon*

#### Past workshops and trainings

[ACCESS Systems mapping course - 12 November - a few spaces still available](https://accessnetwork.uk/systems-mapping-for-environmental-domains-one-day-workshop/)

*Systems Thinking Masterclasses (Fully booked)*

Systems mapping workshop 2024, organised in partnership with INET Oxford and the Cascade Institute.

Tipping points workshop 2024, organised in partnership with INET Oxford and the Cascade Institute.

Systems thinking workshop 2023, organised in partnership with the School of Geography and the Environment, Oxford.

